apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookvault-dep
  namespace: bookvault-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/book-vault/backend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      - name: fluentd
        image: ghcr.io/book-vault/fluentd:v1
        env:
        - name: FLUENTD_CONF
          value: "fluent.conf"
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
        - name: fluentd-config
          mountPath: /fluentd/etc
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: app-logs
        emptyDir: {}
      - name: fluentd-config
        configMap:
          name: fluentd-config
      imagePullSecrets:
      - name: ghcr-secret
