apiVersion: v1
kind: Service
metadata:
  name: bookvault-svc
  namespace: bookvault-ns
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP